Finalized arbiter support

diff --git a/charts/mongodb/templates/scripts.yaml b/charts/mongodb/templates/scripts.yaml
--- a/charts/mongodb/templates/scripts.yaml
+++ b/charts/mongodb/templates/scripts.yaml
@@ -47,7 +47,7 @@ data:
         if [ ! -z "$mp" ]; then
           break;
         fi
-        (( retries-- ))
+        retries=$((retries-1))
         if [ "$retries" -le 0 ]; then
           log "mongod is not running.. Stopping hard"
           kill -STOP 1
@@ -73,7 +73,10 @@ data:
       local primary=$1
       local replicaset=$2
       $MONGOSHELL --eval "rs.initiate({_id:\"$replicaset\",members:[{_id:0, host:\"$primary\"}]})"
-      # //TODO: add error check
+      result=$?
+      if [ $result -ne 0 ]; then
+        log "Failed to init primary - Ignoring errorcode $result, because primary may have existed before: $result"
+      fi
       log "$primary initialized as primary instance"
     }
 
@@ -97,10 +100,59 @@ data:
       if [ "$result" = "0" ]; then
         log "Add $secondary as secondary instance"
         $MONGOSHELL --host $primary --eval "rs.add({host:\"$secondary\"})"
-        # //TODO: add error check
+        result=$?
+        if [ $result -ne 0 ]; then
+          log "Failed to add secondary to ReplicaSet - Exiting with errorcode: $result"
+          exit $result
+        fi
         log "$secondary added to ReplicaSet"
       else
         log "Secondary instance $secondary already in ReplicaSet - doing nothing"
+      fi
+    }
+
+    # Adds an arbiter instance to the ReplicaSet
+    # $1 - FQDN of primary instance for script execution
+    # $2 - FQDN of the arbiter instance which should be added to the ReplicaSet
+    add_arbiter() {
+      local primary=$1
+      local arbiter=$2
+      local result=$(detect_secondary $primary $arbiter)
+      if [ "$result" = "0" ]; then
+        log "Add $arbiter as arbiter instance"
+        $MONGOSHELL --host $primary --eval "db.adminCommand({\"setDefaultRWConcern\" : 1,\"defaultWriteConcern\" : {\"w\" : 1}})"
+        result=$?
+        if [ $result -ne 0 ]; then
+          log "Failed to configure write concern - Exiting with errorcode: $result"
+          exit $result
+        else
+          $MONGOSHELL --host $primary --eval "rs.addArb(\"$arbiter\")"
+          result=$?
+          if [ $result -ne 0 ]; then
+            log "Failed to add arbiter - Exiting with errorcode: $result"
+            exit $result
+          fi
+        fi
+        log "$arbiter added to ReplicaSet as arbiter"
+      else
+        log "Arbiter instance $arbiter already in ReplicaSet - doing nothing"
+      fi
+    }
+
+    # $1 - FQDN of the headless service for this MongoDB cluster
+    # $2 - FQDN of the headless arbiter service for this MongoDB cluster
+    init_arbiter() {
+      local service=$1
+      local arbiter_service=$2
+      local delay=$3
+      local primary=$(find_primary $service)
+      if [ ! -z "$primary" ]; then
+        log "Primary $primary found - Adding this instance as arbiter"
+        add_arbiter $primary "$HOSTNAME.$arbiter_service"
+      else
+        log "ERROR: Primary not found - Waiting $delay seconds before retry"
+        sleep $delay
+        exit 1
       fi
     }
 
@@ -131,12 +183,12 @@ data:
       local signal=$2
       local delay=$3
       log "Terminating entrypoint"
+      kill -s $signal $childproc
       if [ ! -z "$delay" ]; then
         log "Waiting $delay seconds before termination..."
         sleep $delay
       fi
       log "Bye bye"
-      kill -s $signal $childproc
     }
 
     init() {
@@ -161,9 +213,13 @@ data:
       docker-entrypoint.sh $@ &
       mongoproc=$!
       log "Entrypoint pid: $mongoproc"
+      {{- if .Values.replicaSet.enabled }}
       wait_ready {{ .Values.replicaSet.extraInit.retries }} {{ .Values.replicaSet.extraInit.delay }}
-      {{- if .Values.replicaSet.enable }}
-      init_replicaset "{{ include "mongodb.fullname" . }}-internal.{{ .Release.Namespace }}.svc.{{ .Values.replicaSet.clusterDomain }}:{{ .Values.service.port }}" "{{ .Values.replicaSet.replicaSetName }}"
+      if [ "$MONGOTYPE" = "ARBITER" ]; then
+        init_arbiter "{{ include "mongodb.fullname" . }}-{{ .Values.service.headlessServiceSuffix }}.{{ .Release.Namespace }}.svc.{{ .Values.replicaSet.clusterDomain }}:{{ .Values.service.port }}" "{{ include "mongodb.fullname" . }}-{{ .Values.replicaSet.arbiter.headlessServiceSuffix }}.{{ .Release.Namespace }}.svc.{{ .Values.replicaSet.clusterDomain }}:{{ .Values.service.port }}" {{ .Values.replicaSet.arbiter.waitForPrimary }}
+      else
+        init_replicaset "{{ include "mongodb.fullname" . }}-{{ .Values.service.headlessServiceSuffix }}.{{ .Release.Namespace }}.svc.{{ .Values.replicaSet.clusterDomain }}:{{ .Values.service.port }}" "{{ .Values.replicaSet.replicaSetName }}"
+      fi
       terminatedelay={{ .Values.replicaSet.shutdown.delay }}
       {{- end }}
       trap "_terminate $mongoproc 15 $terminatedelay" 15
@@ -202,7 +258,7 @@ data:
       echo "Add extra configs to custom mongodb config"
       cat /extraconfigs/* >>/configs/custom.conf
     fi
-    {{- if .Values.replicaSet.enable }}
+    {{- if .Values.replicaSet.enabled }}
     # //TODO: Allow replicaSet key from secret
     echo "Copy replicaset key"
     echo "{{ .Values.replicaSet.key }}" > /replicaset/keyfile
@@ -210,4 +266,4 @@ data:
     {{- end }}
     echo "Initialization done."
 
-    # //TODO: Allow arbiter and hidden
+    # //TODO: Allow hidden secondaries
