Improved error handling during cluster detection and initialization

diff --git a/charts/mongodb/templates/scripts.yaml b/charts/mongodb/templates/scripts.yaml
--- a/charts/mongodb/templates/scripts.yaml
+++ b/charts/mongodb/templates/scripts.yaml
@@ -37,33 +37,51 @@ data:
     # see "replicaSet.extraInit" in values.yaml
     # $1 - Number of retries
     # $2 - Delay between retries
+    # $3 - Time to wait until mongod is initialized
     wait_ready() {
       log "Waiting until mongod is fully up and running"
       local retries=$1
       local delay=$2
+      local initdelay=$3
       while true; do
         mp=$(ps aux | grep "mongod --config /etc/mongo/custom.conf" | grep -v grep)
-        sleep $delay
         if [ ! -z "$mp" ]; then
+          log "mongod is running giving it time to initialize"
+          sleep $initdelay
           break;
         fi
         retries=$((retries-1))
         if [ "$retries" -le 0 ]; then
           log "mongod is not running.. Stopping hard"
-          kill -STOP 1
           exit 1
         fi
+        sleep $delay
         log "Waiting for mongod..."
       done
-      log "mongod is running"
+      log "Done with waiting for mongod"
+    }
+
+    # Try to detect if there are other instances of this ReplicaSet cluster running
+    # $1 - FQDN of the headless service for this MongoDB cluster
+    # returns - 0 when cluster exists otherwise errorcode
+    detect_cluster() {
+      local service=$1
+      $MONGOSHELL --host $service --eval "db.version"
+      result=$?
+      if [ $result -eq 0 ]; then
+        log "ReplicaSet cluster found"
+      else
+        log "No ReplicaSet cluster detected"
+      fi
+      return $result
     }
 
     # Try to find primary instance of ReplicaSet
     # $1 - FQDN of the headless service for this MongoDB cluster
-    # $? - FQDN of primary instance or empty
+    # returns - FQDN of primary instance or empty
     find_primary() {
       local service=$1
-      result=$($MONGOSHELL --host $service --eval "rs.status().members.filter(function(rs) { return rs.stateStr==='PRIMARY';})[0].name")
+      result=$($MONGOSHELL --host $service --eval "rs.status().members.filter(function(rs) { return rs.state==1;})[0].name")
       returncode=$?
       if [ $returncode -eq 0 ]; then
         echo $result
@@ -78,27 +96,36 @@ data:
     init_primary() {
       local primary=$1
       local replicaset=$2
-      $MONGOSHELL --eval "rs.initiate({_id:\"$replicaset\",members:[{_id:0, host:\"$primary\"}]})"
-      result=$?
-      if [ $result -ne 0 ]; then
-        log "Failed to init primary - Ignoring errorcode $result, because primary may have existed before: $result"
+      # Try to find out if there was an initialized replicaset before (using local instance)
+      result=$($MONGOSHELL --eval "rs.status().members.filter(function(rs) { return rs.name===\"$primary\";}).length")
+      if [ "$result" = "1" ]; then
+        log "Instance $primary was in ReplicaSet before - doing nothing"
+      else
+        # Initialize local instance as primary
+        $MONGOSHELL --eval "rs.initiate({_id:\"$replicaset\",members:[{_id:0, host:\"$primary\"}]})"
+        result=$?
+        if [ $result -ne 0 ]; then
+          log "Failed to init PRIMARY - Exiting with errorcode: $result"
+          exit $result
+        else
+          log "$primary initialized as PRIMARY instance"
+        fi        
       fi
-      log "$primary initialized as primary instance"
     }
 
-    # Detects if a secondary instance with given name exists
+    # Detects if an instance with given name exists
     # $1 - FQDN of primary instance for script execution
-    # $2 - FQDN of the secondary instance to find
-    # $? - "0" if no secondary instance was found - otherwise "1"
-    detect_secondary() {
+    # $2 - FQDN of the instance instance to find
+    # returns - "0" if no instance was found - otherwise "1"
+    detect_instance() {
       local primary=$1
-      local secondary=$2
-      result=$($MONGOSHELL --host $primary --eval "rs.status().members.filter(function(rs) { return rs.name===\"$secondary\";}).length")
+      local instance=$2
+      result=$($MONGOSHELL --host $primary --eval "rs.status().members.filter(function(rs) { return rs.name===\"$instance\";}).length")
       returncode=$?
       if [ $returncode -eq 0 ]; then
         echo $result
       else
-        log "Failed to query for instance $secondary in ReplicaSet - Exiting with errorcode: $returncode"
+        log "Failed to query for instance $instance in ReplicaSet - PRIMARY not ready? - Exiting with errorcode: $returncode"
         exit $returncode
       fi      
     }
@@ -109,18 +136,18 @@ data:
     add_secondary() {
       local primary=$1
       local secondary=$2
-      local result=$(detect_secondary $primary $secondary)
+      local result=$(detect_instance $primary $secondary)
       if [ "$result" = "0" ]; then
-        log "Add $secondary as secondary instance"
+        log "Add $secondary as SECONDARY instance"
         $MONGOSHELL --host $primary --eval "rs.add({host:\"$secondary\"})"
         result=$?
         if [ $result -ne 0 ]; then
-          log "Failed to add secondary to ReplicaSet - Exiting with errorcode: $result"
+          log "Failed to add secondary to ReplicaSet - PRIMARY not ready? - Exiting with errorcode: $result"
           exit $result
         fi
         log "$secondary added to ReplicaSet"
       else
-        log "Secondary instance $secondary already in ReplicaSet - doing nothing"
+        log "SECONDARY instance $secondary already in ReplicaSet - doing nothing"
       fi
     }
 
@@ -130,23 +157,23 @@ data:
     add_arbiter() {
       local primary=$1
       local arbiter=$2
-      local result=$(detect_secondary $primary $arbiter)
+      local result=$(detect_instance $primary $arbiter)
       if [ "$result" = "0" ]; then
-        log "Add $arbiter as arbiter instance"
+        log "Add $arbiter as ARBITER instance"
         $MONGOSHELL --host $primary --eval "db.adminCommand({\"setDefaultRWConcern\" : 1,\"defaultWriteConcern\" : {\"w\" : 1}})"
         result=$?
         if [ $result -ne 0 ]; then
-          log "Failed to configure write concern - Exiting with errorcode: $result"
+          log "Failed to configure write concern - PRIMARY not ready? - Exiting with errorcode: $result"
           exit $result
         else
           $MONGOSHELL --host $primary --eval "rs.addArb(\"$arbiter\")"
           result=$?
           if [ $result -ne 0 ]; then
-            log "Failed to add arbiter - Exiting with errorcode: $result"
+            log "Failed to add ARBITER - PRIMARY not ready? - Exiting with errorcode: $result"
             exit $result
           fi
         fi
-        log "$arbiter added to ReplicaSet as arbiter"
+        log "$arbiter added to ReplicaSet as ARBITER"
       else
         log "Arbiter instance $arbiter already in ReplicaSet - doing nothing"
       fi
@@ -158,14 +185,21 @@ data:
       local service=$1
       local arbiter_service=$2
       local delay=$3
-      local primary=$(find_primary $service)
-      if [ ! -z "$primary" ]; then
-        log "Primary $primary found - Adding this instance as arbiter"
-        add_arbiter $primary "$HOSTNAME.$arbiter_service"
+      detect_cluster $service
+      if [ $? -eq 0 ]; then
+        local primary=$(find_primary $service)
+        if [ ! -z "$primary" ]; then
+          log "Primary $primary found - Adding this instance as ARBITER"
+          add_arbiter $primary "$HOSTNAME.$arbiter_service"
+        else
+          log "ERROR: Primary not found - Waiting $delay seconds before retry"
+          sleep $delay
+          exit 1
+        fi
       else
-        log "ERROR: Primary not found - Waiting $delay seconds before retry"
-        sleep $delay
-        exit 1
+          log "ERROR: ReplicaSet cluster not running - Waiting $delay seconds before retry"
+          sleep $delay
+          exit 1
       fi
     }
 
@@ -176,13 +210,28 @@ data:
       log "Start ReplicaSet initialization"
       local service=$1
       local replicaset=$2
-      local primary=$(find_primary $service)
-      if [ -z "$primary" ]; then
-        log "Primary not found - Initializing this instance as primary"
-        init_primary "$HOSTNAME.$service" $replicaset
+      # First try to detect if other instance of this ReplicSet cluster are available
+      detect_cluster $service
+      if [ $? -eq 0 ]; then
+        # Try to find the primary instance
+        local primary=$(find_primary $service)
+        if [ -z "$primary" ]; then
+          log "Primary not found - Trying to detect if this instance was PRIMARY before"
+          result=$(detect_instance $service "$HOSTNAME.$service")
+          # Find out whether the actual instance was the primary before
+          if [ "$result" = "0" ]; then
+            log "Not the PRIMARY - Can't add this instance $HOSTNAME.$service without a running PRIMARY - Exiting"
+            exit 1
+          else
+            log "This instance $HOSTNAME.$service was the PRIMARY before - Continue starting..."
+          fi
+        else
+          log "Primary $primary found"
+          add_secondary $primary "$HOSTNAME.$service"
+        fi
       else
-        log "Primary $primary found - Adding this instance as secondary"
-        add_secondary $primary "$HOSTNAME.$service"
+        # Assume that this is the first instance in the cluster - initialize it as primary 
+        init_primary "$HOSTNAME.$service" $replicaset
       fi
       log "Done with ReplicaSet initialization\n-----"
     }
@@ -227,7 +276,7 @@ data:
       mongoproc=$!
       log "Entrypoint pid: $mongoproc"
       {{- if .Values.replicaSet.enabled }}
-      wait_ready {{ .Values.replicaSet.extraInit.retries }} {{ .Values.replicaSet.extraInit.delay }}
+      wait_ready {{ .Values.replicaSet.extraInit.retries }} {{ .Values.replicaSet.extraInit.delay }} {{ .Values.replicaSet.extraInit.initDelay }}
       if [ "$MONGOTYPE" = "ARBITER" ]; then
         init_arbiter "{{ include "mongodb.fullname" . }}-{{ .Values.service.headlessServiceSuffix }}.{{ .Release.Namespace }}.svc.{{ .Values.replicaSet.clusterDomain }}:{{ .Values.service.port }}" "{{ include "mongodb.fullname" . }}-{{ .Values.replicaSet.arbiter.headlessServiceSuffix }}.{{ .Release.Namespace }}.svc.{{ .Values.replicaSet.clusterDomain }}:{{ .Values.service.port }}" {{ .Values.replicaSet.arbiter.waitForPrimary }}
       else
