Improved master detection logic and forced failover

diff --git a/charts/redis/templates/scripts.yaml b/charts/redis/templates/scripts.yaml
--- a/charts/redis/templates/scripts.yaml
+++ b/charts/redis/templates/scripts.yaml
@@ -8,18 +8,27 @@ data:
   init.sh: |
     #!/bin/sh
   {{- if .Values.haMode.enabled }}
-    MASTER="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel get-master-addr-by-name {{ include "redis.masterGroupName" . }} | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
+    MASTER="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel get-master-addr-by-name {{ include "redis.masterGroupName" . }} | head -n 1)"
   {{- end }}
     REDIS_CONFIG=/data/conf/redis.conf
     SENTINEL_CONFIG=/data/conf/sentinel.conf
 
   {{- if .Values.haMode.enabled }}
     test_master_alive() {
-        TEST="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h $MASTER -p 6379 ping)"
-        if [ -z "$TEST" ]; then
-          return 1
-        fi
-        return 0
+      echo "Checking if master is alive"
+      TEST="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h $MASTER -p 6379 ping)"
+      if [ -z "$TEST" ]; then
+        return 1
+      fi
+      return 0
+    }
+
+    test_valid_dns() {
+      {{- if .Values.haMode.useDnsNames }}
+      MASTERENTRY="$(getent hosts $MASTER | awk '{ print $2 }')"
+      {{- else }}
+      MASTERENTRY="$(getent hosts $MASTER | awk '{ print $1 }')"
+      {{- end }}
     }
   {{- end }}
 
@@ -35,22 +44,42 @@ data:
 
   {{- if .Values.haMode.enabled }}
         if [ -z "$MASTER" ]; then
-            echo "No master found - This instance ($HOSTNAME) will be master now"
+          echo "No master found - This instance ($HOSTNAME) will be master now"
         else
-            echo "Redis master was found with address $MASTER - Checking if master is still alive "
+          echo "Redis master was found with address $MASTER - Checking host dns entry"
+          test_valid_dns
+          if [ -z "$MASTERENTRY" ]; then
+            if [ -f "/data/failover_restart" ]; then
+              rm /data/failover_restart
+              echo "Forcing failover now"
+              redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
+            else
+              echo "No valid DNS entry found! - waiting for failover"
+              sleep {{ .Values.haMode.failoverWait }}
+              touch /data/failover_restart
+            fi
+            exit 1
+          else
+            MASTER=$MASTERENTRY
+            echo "$MASTER has valid DNS entry"
             test_master_alive
             if [ "$?" -eq "1" ]; then
-              echo "Dead master at address $MASTER detected! - waiting for failover"
-              sleep {{ .Values.haMode.failoverWait }}
-              test_master_alive
-              if [ "$?" -eq "1" ]; then
+              if [ -f "/data/failover_restart" ]; then
+                rm /data/failover_restart
                 echo "Master is still dead! - forcing failover and retry pod initialization"
                 redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
-                exit 1
+              else
+                echo "Dead master at address $MASTER detected! - waiting for failover"
+                sleep {{ .Values.haMode.failoverWait }}
+                touch /data/failover_restart
               fi
+              exit 1
+            else
+              rm -f /data/failover_restart
+              echo "Setting this instance ($HOSTNAME) as replicaof $MASTER"
+              echo "replicaof $MASTER 6379" >>$REDIS_CONFIG
             fi
-            echo "Setting this instance ($HOSTNAME) as replicaof $MASTER"
-            echo "replicaof $MASTER 6379" >>$REDIS_CONFIG
+          fi
         fi
   {{- end }}
 
@@ -72,13 +101,21 @@ data:
 
         echo "Setting sentinel defaults"
         if [ -z "$MASTER" ]; then
-          MASTER_IP="$(getent hosts $HOSTNAME | awk '{ print $1 }')"
-          echo "No master found - Configuring sentinel for master $HOSTNAME with address $MASTER_IP"
-          echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER_IP 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
+          {{- if .Values.haMode.useDnsNames }}
+          MASTER=${HOSTNAME}.{{ include "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
+          {{- else }}
+          MASTER="$(getent hosts $HOSTNAME | awk '{ print $1 }')"
+          {{- end }}
+          echo "No master found - Configuring sentinel for master $HOSTNAME with address $MASTER"
+          echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
         else
           echo "Redis master was found - Configuring sentinel for master address $MASTER"
           echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
         fi
+        {{- if .Values.haMode.useDnsNames }}
+        echo "SENTINEL resolve-hostnames yes" >>$SENTINEL_CONFIG
+        echo "SENTINEL announce-hostnames yes" >>$SENTINEL_CONFIG
+        {{- end }}
         echo "sentinel down-after-milliseconds {{ include "redis.masterGroupName" . }} {{ .Values.haMode.downAfterMilliseconds }}" >>$SENTINEL_CONFIG
         echo "sentinel failover-timeout {{ include "redis.masterGroupName" . }} {{ .Values.haMode.failoverTimeout }}" >>$SENTINEL_CONFIG
         
