Improved logging and failover detection during Redis-HA initialization (#1194)
* Improved master detection logic and forced failover

* Rearranged script order

* Improved logging and failover detection

* Fixed trailing spaces

diff --git a/charts/redis/templates/scripts.yaml b/charts/redis/templates/scripts.yaml
--- a/charts/redis/templates/scripts.yaml
+++ b/charts/redis/templates/scripts.yaml
@@ -6,98 +6,167 @@ metadata:
     {{- include "redis.labels" . | nindent 4 }}
 data:
   init.sh: |
-    #!/bin/sh
-  {{- if .Values.haMode.enabled }}
-    MASTER="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel get-master-addr-by-name {{ include "redis.masterGroupName" . }} | grep -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
-  {{- end }}
+    #!/bin/bash
     REDIS_CONFIG=/data/conf/redis.conf
     SENTINEL_CONFIG=/data/conf/sentinel.conf
+    if [ -f "/data/init.log" ]; then
+      echo "Detected restart of this instance ($HOSTNAME)"
+      echo "## This was the previous log:"
+      cat /data/init.log
+      echo "## End of previous log"
+    fi
 
-  {{- if .Values.haMode.enabled }}
+    # Log a message during initialization phase
+    # $1 - the log message
+    log() {
+      echo "$(date) $1"
+      echo "$(date) $1" >>/data/init.log
+    }
+
+    # Creating redis base configuration
+    configure_redis_base() {
+      log "Creating redis base configuration"
+      mkdir -p /data/conf
+      rm -f $REDIS_CONFIG
+
+      log "Setting redis server defaults"
+      echo "port 6379" >>$REDIS_CONFIG
+      echo "protected-mode no" >>$REDIS_CONFIG
+      echo "bind 0.0.0.0" >>$REDIS_CONFIG
+      echo "dir /data" >>$REDIS_CONFIG
+      log "Finished creating base configuration"
+    }
+
+    configure_redis_ext() {
+      if [ -f /usr/local/etc/redis/redis.conf ]; then
+          log "Adding optional redis configuration"
+          cat /usr/local/etc/redis/redis.conf >>$REDIS_CONFIG
+      fi
+      if [ -d /extraredisconfigs ]; then
+        log "Adding extra redis configs to redis configuration"
+        cat /extraredisconfigs/* >>$REDIS_CONFIG
+      fi
+    }
+
     test_master_alive() {
-        TEST="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h $MASTER -p 6379 ping)"
-        if [ -z "$TEST" ]; then
-          return 1
-        fi
-        return 0
+      TEST="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h $MASTER -p 6379 ping)"
+      if [ -z "$TEST" ]; then
+        log "Master is not alive"
+        return 1
+      fi
+      log "Master is alive"
+      return 0
     }
-  {{- end }}
 
-    configure_redis() {
-        echo "Configuring redis server..."
-        rm -f $REDIS_CONFIG
-
-        echo "Setting redis server defaults"
-        echo "port 6379" >>$REDIS_CONFIG
-        echo "protected-mode no" >>$REDIS_CONFIG
-        echo "bind 0.0.0.0" >>$REDIS_CONFIG
-        echo "dir /data" >>$REDIS_CONFIG
-
-  {{- if .Values.haMode.enabled }}
-        if [ -z "$MASTER" ]; then
-            echo "No master found - This instance ($HOSTNAME) will be master now"
-        else
-            echo "Redis master was found with address $MASTER - Checking if master is still alive "
-            test_master_alive
-            if [ "$?" -eq "1" ]; then
-              echo "Dead master at address $MASTER detected! - waiting for failover"
-              sleep {{ .Values.haMode.failoverWait }}
-              test_master_alive
-              if [ "$?" -eq "1" ]; then
-                echo "Master is still dead! - forcing failover and retry pod initialization"
-                redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
-                exit 1
-              fi
-            fi
-            echo "Setting this instance ($HOSTNAME) as replicaof $MASTER"
-            echo "replicaof $MASTER 6379" >>$REDIS_CONFIG
-        fi
-  {{- end }}
-
-        if [ -f /usr/local/etc/redis/redis.conf ]; then
-            echo "Adding optional redis configuration settings"
-            cat /usr/local/etc/redis/redis.conf >>$REDIS_CONFIG
-        fi
-        if [ -d /extraredisconfigs ]; then
-          echo "Adding extra redis configs to redis configuration"
-          cat /extraredisconfigs/* >>$REDIS_CONFIG
-        fi
-        echo "Configuring redis server finished."
+    test_valid_dns() {
+      KNOWN_HOSTS=($(getent hosts {{ include "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }} | awk '{ print $1 }'))
+      log "## Known hosts for headless service {{ include "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:"
+      for AHOSTIP in "${KNOWN_HOSTS[@]}"; do
+        AHOSTNAME=$(getent hosts $AHOSTIP | awk '{print $2}')
+        log "${AHOSTIP} ${AHOSTNAME}"
+      done
+      log "#####"
+      {{- if .Values.haMode.useDnsNames }}
+      MASTERENTRY="$(getent hosts $MASTER | awk '{ print $2 }')"
+      {{- else }}
+      MASTERENTRY="$(getent hosts $MASTER | awk '{ print $1 }')"
+      {{- end }}
     }
-  {{- if .Values.haMode.enabled }}
+
     configure_sentinel() {
-        echo "Redis HA-mode enabled"
-        echo "Configuring sentinel server..."
-        rm -f $SENTINEL_CONFIG
+      log "Configuring sentinel server..."
+      rm -f $SENTINEL_CONFIG
 
-        echo "Setting sentinel defaults"
-        if [ -z "$MASTER" ]; then
-          MASTER_IP="$(getent hosts $HOSTNAME | awk '{ print $1 }')"
-          echo "No master found - Configuring sentinel for master $HOSTNAME with address $MASTER_IP"
-          echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER_IP 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
-        else
-          echo "Redis master was found - Configuring sentinel for master address $MASTER"
-          echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
-        fi
-        echo "sentinel down-after-milliseconds {{ include "redis.masterGroupName" . }} {{ .Values.haMode.downAfterMilliseconds }}" >>$SENTINEL_CONFIG
-        echo "sentinel failover-timeout {{ include "redis.masterGroupName" . }} {{ .Values.haMode.failoverTimeout }}" >>$SENTINEL_CONFIG
-        
-        if [ -f /usr/local/etc/redis/sentinel.conf ]; then
-            echo "Adding optional sentinel configuration settings"
-            cat /usr/local/etc/redis/sentinel.conf >>$SENTINEL_CONFIG
-        fi
-        if [ -d /extrasentinelconfigs ]; then
-          echo "Adding extra sentinel configs to sentinel configuration"
-          cat /extrasentinelconfigs/* >>$SENTINEL_CONFIG
-        fi
-        echo "Configuring sentinel server finished."
+      log "Setting sentinel defaults"
+      if [ -z "$MASTER" ]; then
+        {{- if .Values.haMode.useDnsNames }}
+        MASTER=${HOSTNAME}.{{ include "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
+        {{- else }}
+        MASTER="$(getent hosts $HOSTNAME | awk '{ print $1 }')"
+        {{- end }}
+        log "No master found - Configuring sentinel for master $HOSTNAME with address $MASTER"
+        echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
+      else
+        log "Redis master was found - Configuring sentinel for master address $MASTER"
+        echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
+      fi
+      {{- if .Values.haMode.useDnsNames }}
+      echo "SENTINEL resolve-hostnames yes" >>$SENTINEL_CONFIG
+      echo "SENTINEL announce-hostnames yes" >>$SENTINEL_CONFIG
+      {{- end }}
+      echo "sentinel down-after-milliseconds {{ include "redis.masterGroupName" . }} {{ .Values.haMode.downAfterMilliseconds }}" >>$SENTINEL_CONFIG
+      echo "sentinel failover-timeout {{ include "redis.masterGroupName" . }} {{ .Values.haMode.failoverTimeout }}" >>$SENTINEL_CONFIG
     }
-  {{- end }}
 
-    echo "Initialize configuration..."
-    mkdir -p /data/conf
-    configure_redis
+    configure_sentinel_ext() {
+      if [ -f /usr/local/etc/redis/sentinel.conf ]; then
+          log "Adding optional sentinel configuration settings"
+          cat /usr/local/etc/redis/sentinel.conf >>$SENTINEL_CONFIG
+      fi
+      if [ -d /extrasentinelconfigs ]; then
+        log "Adding extra sentinel configs to sentinel configuration"
+        cat /extrasentinelconfigs/* >>$SENTINEL_CONFIG
+      fi
+      log "Configuring sentinel server finished."
+    }
+
+    configure_redis_cluster() {
+      log "Try to detect cluster master.."
+      MASTER="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel get-master-addr-by-name {{ include "redis.masterGroupName" . }} | head -n 1)"
+      if [ -z "$MASTER" ]; then
+        log "No master found - This instance ($HOSTNAME) will be master now"
+      else
+        log "Redis master was found with address $MASTER - Checking host dns entry"
+        test_valid_dns
+        if [ -z "$MASTERENTRY" ]; then
+          log "No valid DNS entry found!"
+          if [ -f "/data/failover_restart" ]; then
+            rm /data/failover_restart
+            log "Forcing failover now"
+            redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
+          else
+            log "Waiting for failover before restart"
+            sleep {{ .Values.haMode.failoverWait }}
+            touch /data/failover_restart
+          fi
+          log "Restart"
+          exit 1
+        else
+          MASTER=$MASTERENTRY
+          log "$MASTER has valid DNS entry"
+          log "Checking if master is alive"
+          test_master_alive
+          if [ "$?" -eq "1" ]; then
+            if [ -f "/data/failover_restart" ]; then
+              rm /data/failover_restart
+              log "Master is still dead! - forcing failover and retry pod initialization"
+              redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
+            else
+              log "Dead master at address $MASTER detected! - waiting for failover"
+              sleep {{ .Values.haMode.failoverWait }}
+              touch /data/failover_restart
+            fi
+            log "Restart"
+            exit 1
+          else
+            rm -f /data/failover_restart
+            log "Setting this instance ($HOSTNAME) as replicaof $MASTER"
+            echo "replicaof $MASTER 6379" >>$REDIS_CONFIG
+          fi
+        fi
+      fi
+    }
+
+    log "Creating configuration..."
+    configure_redis_base
   {{- if .Values.haMode.enabled }}
+    log "Redis HA-mode is enabled"
+    configure_redis_cluster
     configure_sentinel
+    configure_sentinel_ext
   {{- end }}
-    echo "Finished."
+    configure_redis_ext
+    log "Done."
+  {{- if not .Values.haMode.keepOldLogs }}
+    rm -f /data/init.log
+  {{- end }}
