Upgrade Redis 8.10.2 + sentinel only instances

diff --git a/charts/redis/templates/scripts.yaml b/charts/redis/templates/scripts.yaml
--- a/charts/redis/templates/scripts.yaml
+++ b/charts/redis/templates/scripts.yaml
@@ -213,3 +213,62 @@ data:
     configure_sentinel
   {{- end }}
     log "Done."
+{{- if and .Values.haMode.enabled (gt (int .Values.haMode.sentinelOnlyReplicas) 0) }}
+  sentinel-init.sh: |
+    #!/bin/sh
+    SENTINEL_CONFIG=/data/conf/sentinel.conf
+
+    log() {
+      echo "$(date) $1"
+    }
+
+    configure_sentinel_ext() {
+      if [ -f /usr/local/etc/redis/sentinel.conf ]; then
+        log "Adding optional sentinel configuration settings"
+        cat /usr/local/etc/redis/sentinel.conf >>$SENTINEL_CONFIG
+      fi
+      if [ -d /extrasentinelconfigs ]; then
+        log "Adding extra sentinel configs to sentinel configuration"
+        cat /extrasentinelconfigs/* >>$SENTINEL_CONFIG
+      fi
+    }
+
+    log "Creating Sentinel-only configuration..."
+    mkdir -p /data/conf
+    : >$SENTINEL_CONFIG
+    configure_sentinel_ext
+
+    SENTINELUSER=$(grep "sentinel sentinel-user" $SENTINEL_CONFIG | awk '{ print $3 }')
+    if [ -n "$SENTINELUSER" ]; then
+      SENTINELUSER="--user $SENTINELUSER"
+    fi
+    SENTINELPWD=$(grep "sentinel sentinel-pass" $SENTINEL_CONFIG | awk '{ print $3 }')
+    if [ -n "$SENTINELPWD" ]; then
+      SENTINELPWD="--pass $SENTINELPWD"
+    fi
+
+    SERVICE="$(getent hosts {{ include "redis.fullname" . }})"
+    if [ -z "$SERVICE" ]; then
+      log "Can't resolve Sentinel service - retrying after {{ .Values.haMode.dnsFailureWait }} seconds"
+      sleep {{ .Values.haMode.dnsFailureWait }}
+      exit 1
+    fi
+
+    MASTER="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h {{ include "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} $SENTINELUSER $SENTINELPWD sentinel get-master-addr-by-name {{ include "redis.masterGroupName" . }} | head -n 1)"
+    if [ -z "$MASTER" ]; then
+      log "No Redis master available - retrying after {{ .Values.haMode.dnsFailureWait }} seconds"
+      sleep {{ .Values.haMode.dnsFailureWait }}
+      exit 1
+    fi
+
+    log "Configuring Sentinel for Redis master $MASTER"
+    echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
+  {{- if .Values.haMode.useDnsNames }}
+    echo "SENTINEL resolve-hostnames yes" >>$SENTINEL_CONFIG
+    echo "SENTINEL announce-hostnames yes" >>$SENTINEL_CONFIG
+  {{- end }}
+    echo "SENTINEL announce-ip ${POD_IP}" >>$SENTINEL_CONFIG
+    echo "sentinel down-after-milliseconds {{ include "redis.masterGroupName" . }} {{ .Values.haMode.downAfterMilliseconds }}" >>$SENTINEL_CONFIG
+    echo "sentinel failover-timeout {{ include "redis.masterGroupName" . }} {{ .Values.haMode.failoverTimeout }}" >>$SENTINEL_CONFIG
+    log "Done."
+{{- end }}
