Rearranged script order

diff --git a/charts/redis/templates/scripts.yaml b/charts/redis/templates/scripts.yaml
--- a/charts/redis/templates/scripts.yaml
+++ b/charts/redis/templates/scripts.yaml
@@ -7,15 +7,21 @@ metadata:
 data:
   init.sh: |
     #!/bin/sh
-  {{- if .Values.haMode.enabled }}
-    MASTER="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel get-master-addr-by-name {{ include "redis.masterGroupName" . }} | head -n 1)"
-  {{- end }}
     REDIS_CONFIG=/data/conf/redis.conf
     SENTINEL_CONFIG=/data/conf/sentinel.conf
 
+    # Log a message during initialization phase
+    # $1 - the log message
+    log() {
+      echo "$(date) $1"
+      echo "$(date) $1" >>/data/init.log
+    }
+
   {{- if .Values.haMode.enabled }}
+    MASTER="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel get-master-addr-by-name {{ include "redis.masterGroupName" . }} | head -n 1)"
+
     test_master_alive() {
-      echo "Checking if master is alive"
+      log "Checking if master is alive"
       TEST="$(timeout {{ .Values.haMode.masterAliveTestTimeout }}s redis-cli -h $MASTER -p 6379 ping)"
       if [ -z "$TEST" ]; then
         return 1
@@ -30,86 +36,23 @@ data:
       MASTERENTRY="$(getent hosts $MASTER | awk '{ print $1 }')"
       {{- end }}
     }
-  {{- end }}
 
-    configure_redis() {
-        echo "Configuring redis server..."
-        rm -f $REDIS_CONFIG
-
-        echo "Setting redis server defaults"
-        echo "port 6379" >>$REDIS_CONFIG
-        echo "protected-mode no" >>$REDIS_CONFIG
-        echo "bind 0.0.0.0" >>$REDIS_CONFIG
-        echo "dir /data" >>$REDIS_CONFIG
-
-  {{- if .Values.haMode.enabled }}
-        if [ -z "$MASTER" ]; then
-          echo "No master found - This instance ($HOSTNAME) will be master now"
-        else
-          echo "Redis master was found with address $MASTER - Checking host dns entry"
-          test_valid_dns
-          if [ -z "$MASTERENTRY" ]; then
-            if [ -f "/data/failover_restart" ]; then
-              rm /data/failover_restart
-              echo "Forcing failover now"
-              redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
-            else
-              echo "No valid DNS entry found! - waiting for failover"
-              sleep {{ .Values.haMode.failoverWait }}
-              touch /data/failover_restart
-            fi
-            exit 1
-          else
-            MASTER=$MASTERENTRY
-            echo "$MASTER has valid DNS entry"
-            test_master_alive
-            if [ "$?" -eq "1" ]; then
-              if [ -f "/data/failover_restart" ]; then
-                rm /data/failover_restart
-                echo "Master is still dead! - forcing failover and retry pod initialization"
-                redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
-              else
-                echo "Dead master at address $MASTER detected! - waiting for failover"
-                sleep {{ .Values.haMode.failoverWait }}
-                touch /data/failover_restart
-              fi
-              exit 1
-            else
-              rm -f /data/failover_restart
-              echo "Setting this instance ($HOSTNAME) as replicaof $MASTER"
-              echo "replicaof $MASTER 6379" >>$REDIS_CONFIG
-            fi
-          fi
-        fi
-  {{- end }}
-
-        if [ -f /usr/local/etc/redis/redis.conf ]; then
-            echo "Adding optional redis configuration settings"
-            cat /usr/local/etc/redis/redis.conf >>$REDIS_CONFIG
-        fi
-        if [ -d /extraredisconfigs ]; then
-          echo "Adding extra redis configs to redis configuration"
-          cat /extraredisconfigs/* >>$REDIS_CONFIG
-        fi
-        echo "Configuring redis server finished."
-    }
-  {{- if .Values.haMode.enabled }}
     configure_sentinel() {
-        echo "Redis HA-mode enabled"
-        echo "Configuring sentinel server..."
+        log "Redis HA-mode enabled"
+        log "Configuring sentinel server..."
         rm -f $SENTINEL_CONFIG
 
-        echo "Setting sentinel defaults"
+        log "Setting sentinel defaults"
         if [ -z "$MASTER" ]; then
           {{- if .Values.haMode.useDnsNames }}
           MASTER=${HOSTNAME}.{{ include "redis.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
           {{- else }}
           MASTER="$(getent hosts $HOSTNAME | awk '{ print $1 }')"
           {{- end }}
-          echo "No master found - Configuring sentinel for master $HOSTNAME with address $MASTER"
+          log "No master found - Configuring sentinel for master $HOSTNAME with address $MASTER"
           echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
         else
-          echo "Redis master was found - Configuring sentinel for master address $MASTER"
+          log "Redis master was found - Configuring sentinel for master address $MASTER"
           echo "sentinel monitor {{ include "redis.masterGroupName" . }} $MASTER 6379 {{ .Values.haMode.quorum }}" >>$SENTINEL_CONFIG
         fi
         {{- if .Values.haMode.useDnsNames }}
@@ -120,21 +63,83 @@ data:
         echo "sentinel failover-timeout {{ include "redis.masterGroupName" . }} {{ .Values.haMode.failoverTimeout }}" >>$SENTINEL_CONFIG
         
         if [ -f /usr/local/etc/redis/sentinel.conf ]; then
-            echo "Adding optional sentinel configuration settings"
+            log "Adding optional sentinel configuration settings"
             cat /usr/local/etc/redis/sentinel.conf >>$SENTINEL_CONFIG
         fi
         if [ -d /extrasentinelconfigs ]; then
-          echo "Adding extra sentinel configs to sentinel configuration"
+          log "Adding extra sentinel configs to sentinel configuration"
           cat /extrasentinelconfigs/* >>$SENTINEL_CONFIG
         fi
-        echo "Configuring sentinel server finished."
+        log "Configuring sentinel server finished."
     }
   {{- end }}
 
-    echo "Initialize configuration..."
+    configure_redis() {
+        log "Configuring redis server..."
+        rm -f $REDIS_CONFIG
+
+        log "Setting redis server defaults"
+        echo "port 6379" >>$REDIS_CONFIG
+        echo "protected-mode no" >>$REDIS_CONFIG
+        echo "bind 0.0.0.0" >>$REDIS_CONFIG
+        echo "dir /data" >>$REDIS_CONFIG
+
+  {{- if .Values.haMode.enabled }}
+        if [ -z "$MASTER" ]; then
+          log "No master found - This instance ($HOSTNAME) will be master now"
+        else
+          log "Redis master was found with address $MASTER - Checking host dns entry"
+          test_valid_dns
+          if [ -z "$MASTERENTRY" ]; then
+            if [ -f "/data/failover_restart" ]; then
+              rm /data/failover_restart
+              log "Forcing failover now"
+              redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
+            else
+              log "No valid DNS entry found! - waiting for failover"
+              sleep {{ .Values.haMode.failoverWait }}
+              touch /data/failover_restart
+            fi
+            exit 1
+          else
+            MASTER=$MASTERENTRY
+            log "$MASTER has valid DNS entry"
+            test_master_alive
+            if [ "$?" -eq "1" ]; then
+              if [ -f "/data/failover_restart" ]; then
+                rm /data/failover_restart
+                log "Master is still dead! - forcing failover and retry pod initialization"
+                redis-cli -h {{ template "redis.fullname" . }} -p {{ .Values.service.sentinelPort }} sentinel failover {{ include "redis.masterGroupName" . }}
+              else
+                log "Dead master at address $MASTER detected! - waiting for failover"
+                sleep {{ .Values.haMode.failoverWait }}
+                touch /data/failover_restart
+              fi
+              exit 1
+            else
+              rm -f /data/failover_restart
+              log "Setting this instance ($HOSTNAME) as replicaof $MASTER"
+              echo "replicaof $MASTER 6379" >>$REDIS_CONFIG
+            fi
+          fi
+        fi
+  {{- end }}
+
+        if [ -f /usr/local/etc/redis/redis.conf ]; then
+            log "Adding optional redis configuration settings"
+            cat /usr/local/etc/redis/redis.conf >>$REDIS_CONFIG
+        fi
+        if [ -d /extraredisconfigs ]; then
+          log "Adding extra redis configs to redis configuration"
+          cat /extraredisconfigs/* >>$REDIS_CONFIG
+        fi
+        log "Configuring redis server finished."
+    }
+
+    log "Initialize configuration..."
     mkdir -p /data/conf
     configure_redis
   {{- if .Values.haMode.enabled }}
     configure_sentinel
   {{- end }}
-    echo "Finished."
+    log "Finished."
